version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: host.docker.internal  # This points to your local machine where MySQL is running
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: 6174@Adarsha
      MYSQL_DB: adarsha
